### ISSUE TITLE
Potential minor bugs in measure_latency.py

### ISSUE THREAD

**Issue by kaikai23** [mit-han-lab/sparsevit#1]
Hi Zhijian, 

Great work! I notice there are 2 minor bugs in `measure_latency.py`. If I misunderstand something or I am wrong, please feel free to correct me.

1. running `python tools/measure_latency.py configs/sparsevit/sparsevit_cfg1_42ms.py --img_size 672` as in the Readme gives an error:
```
  File "/home/xxxx/sparsevit/tools/measure_latency.py", line 74, in parse_args
    if args.options and args.eval_options:
AttributeError: 'Namespace' object has no attribute 'options'
```
For me, adding the options, eval_options and cfg_options can pass this error.

2. the function `select` in `measure_latency.py` doesn't change the model part as the `sparsevit_cfg1_42ms.py` uses SwinTransformer but SparseViT as backbone. As a result, the tested three models (`sparsevit_cfg1_42ms.py`, `sparsevit_cfg2_35ms`, `sparsevit_cfg3_33ms`) seem to output the same latency. 
 
I suspect this can be easily fixed by providing a correct config file. Would you mind taking some time to check it?

**Comment by xyaochen** [comment]
Apologies for the oversight. To rectify this, please modify the `_base_` entry in the config to:
```
_base_ = './mask_rcnn_sparsevit.py'
```

I appreciate your attention to this detail.
